[package]
name = "gsl_rust"
author = "Pim van den Berg"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5"
drop_guard = "0.3.0"

[dev-dependencies]
fastrand = "1.6"

[build-dependencies]
bindgen = "0.59.2"
cmake = "0.1"